In [11]:
import numpy as np

class Perceptron:
    def __init__(self, entradas, salidas ):
        self.entradas_rna = np.array(entradas)
        self.salidas_rna = np.array(salidas)
        
    def optimizar_pesos(self):
        epocas, num_entradas = 0, 0 
        while num_entradas < 4:
            print('-------iteracion {}'.format(epocas))
            pesos = np.array(np.random.uniform(-1,1, self.entradas_rna.shape))
            for entrada_red, peso, salida_red in zip(self.entradas_rna, pesos, self.salidas_rna):
                salida_generada = entrada_red@peso
                print(salida_generada)
                salida_generada = 0 if salida_generada < 0 else 1
                if salida_generada == salida_red:
                    num_entradas +=1
                else:
                    num_entradas=0
                    
                print('entrada \n', entrada_red, ' pesos: \n', peso, ' salida esperada \n',salida_red, 'salida obtenida: \n', salida_generada)
        
        epocas +=1
        return True 

In [12]:
if __name__ == '__main__':
    entradas = [
        [0,0,1],
        [0,1,1],
        [1,0,1],
        [1,1,1]        
    ]
    salidas = [0,0,0,1]
    perceptron = Perceptron(entradas, salidas)
    perceptron.optimizar_pesos()

-------iteracion 0
0.58368511458269
entrada 
 [0 0 1]  pesos: 
 [-0.58137851 -0.60109509  0.58368511]  salida esperada 
 0 salida obtenida: 
 1
0.24380247277305678
entrada 
 [0 1 1]  pesos: 
 [ 0.11942599  0.29660296 -0.05280049]  salida esperada 
 0 salida obtenida: 
 1
-0.7558270953921513
entrada 
 [1 0 1]  pesos: 
 [-0.78787512  0.35121027  0.03204803]  salida esperada 
 0 salida obtenida: 
 0
0.25830134269030003
entrada 
 [1 1 1]  pesos: 
 [ 0.9934607  -0.34604426 -0.38911511]  salida esperada 
 1 salida obtenida: 
 1
-------iteracion 0
-0.976940153837992
entrada 
 [0 0 1]  pesos: 
 [-0.90011029  0.62532225 -0.97694015]  salida esperada 
 0 salida obtenida: 
 0
-0.7319191375945724
entrada 
 [0 1 1]  pesos: 
 [-0.0069821  -0.32744823 -0.40447091]  salida esperada 
 0 salida obtenida: 
 0
-0.21369615832082434
entrada 
 [1 0 1]  pesos: 
 [-0.60239203 -0.51267653  0.38869587]  salida esperada 
 0 salida obtenida: 
 0
0.9756067120252712
entrada 
 [1 1 1]  pesos: 
 [ 0.9436368  -0.317538